### ISSUE TITLE
Make for windows and or chrome extension

### ISSUE THREAD

**Issue by dsmith37137** [liudongmiao/bible#11]
I have really loved your bible as it's the only one to still get the niv84. However with android I'm now switching to the new windows 10 and have been trying to use this in there. They now use apps, or the Google chrome also uses apps but not apk files and i have tried to use a few to use apk in the browser apps or on windows with no luck. If you write the reader to chrome ext. that way you can use on anything that can install chrome.

**Comment by liudongmiao** [comment]
you can visit a archive of the old version: http://web.archive.org/web/20130123213725/http://www.biblegateway.com/versions/index.php?action=getVersionInfo&vid=102
