### ISSUE TITLE
How to run it on PC

### ISSUE THREAD

**Issue by xuchi7** [liudongmiao/bible#14]
It a nice work! Can I run the app on PC (windows or ubuntu)? 
Thanks

**Comment by wajeemba** [comment]
You could try running it inside a virtual machine (vm). Google for the
Android-x86 project and how to set it up as a vm. There may even be
Android-x86 prepackaged vm's.
Then sideload the bible apk. :)

**Comment by xuchi7** [comment]
thanks for the reply
:)

Besides, I have a question about the Chinese Bible (和合本). Is it possible to show the small titles of paragraphs inside each chapter in the app?

**Comment by liudongmiao** [comment]
I don't recommend you run on PC.

You can just visit original web version, on biblegateway.com or bibles.org.
