### ISSUE TITLE
How to download a translation of the bible

### ISSUE THREAD

**Issue by yeongnamtan** [liudongmiao/bible#21]
i run below python command but get error:

python download-bgw.py https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/

PS C:\Users\yeong> python download-bgw.py https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/
open https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/ ...
Traceback (most recent call last):
  File "C:\Users\yeong\download-bgw.py", line 563, in <module>
    bible = BIBLEGATE(version)
  File "C:\Users\yeong\download-bgw.py", line 274, in __init__
    book = ''.join(self.get_books()[:1])
  File "C:\Users\yeong\download-bgw.py", line 382, in get_books
    self.version_fullname = re_current.findall(page)[0]
IndexError: list index out of range

**Comment by liudongmiao** [comment]
Please don't report these errors. It will violate the terms of biblegateway.com.

**Comment by liudongmiao** [comment]
If you still like ESV, you can help to contact the copyright owner.

We have been asked to stop sending esv files, even via email for personal use.

**Comment by yeongnamtan** [comment]
thank you very much. Noted.
